### ISSUE TITLE
themes/bear/layout/archive.pug:5 执行hexo g报错！

### ISSUE THREAD

**Issue by svenbarnett** [gary-Shen/hexo-theme-curry#10]
ERROR TypeError: /Users/svenbarnett/Desktop/blogfile/themes/bear/layout/archive.pug:5
    3| block content
    4|   .container
  > 5|     - const _posts=((e=[])=>{return e.filter(e=>!page.year||e.date.year()===page.year).forEach(e=>{const a=e.date.year();(void 0)[a]||((void 0)[a]=[]),(void 0)[a].push(e)}),Object.keys(void 0).sort(e=>-e).map(e=>(void 0)[e])})(site.posts.data);
    6|     each group in _posts
    7|       .year-wrap
    8|         .year

Cannot read properties of undefined (reading '2021')
    at eval (eval at wrap (/Users/svenbarnett/Desktop/blogfile/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:183:124)
    at Array.forEach (<anonymous>)
    at eval (eval at wrap (/Users/svenbarnett/Desktop/blogfile/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:183:82)

**Comment by gary-Shen** [comment]
抱歉现在才看到。
我修正下，稍等哈

**Comment by gary-Shen** [comment]
抱歉现在才看到。我看看哈

**Comment by gary-Shen** [comment]
已修正，谢谢。
请在主题下 `git pull` 更新看看。
